namespace Diva.Agents.Hooks.BuiltIn;

using Diva.Core.Models;

/// <summary>
/// Appends a configurable disclaimer to the agent's response.
/// Configure the disclaimer text via agent custom variable "disclaimer_text".
/// If no variable is set, uses a generic AI-generated content disclaimer.
/// </summary>
public sealed class DisclaimerAppenderHook : IOnBeforeResponseHook
{
    private const string DefaultDisclaimer =
        "This response was generated by an AI assistant and should be verified " +
        "before being used for decision-making purposes.";

    public int Order => 90; // Run late — after content hooks but before PII redaction

    public Task<string> OnBeforeResponseAsync(
        AgentHookContext context, string responseText, CancellationToken ct)
    {
        var disclaimer = context.Variables.GetValueOrDefault("disclaimer_text", DefaultDisclaimer);

        return Task.FromResult(responseText + "\n\n---\n*" + disclaimer + "*");
    }
}
