// <auto-generated />
using System;
using Diva.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diva.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DivaDbContext))]
    [Migration("20260327100000_Phase16_RulePacks")]
    partial class Phase16_RulePacks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            // Snapshot copied from DivaDbContextModelSnapshot + new entities.
            // Only the new entities are listed here; the full snapshot is maintained
            // by the DivaDbContextModelSnapshot file.

            modelBuilder.Entity("Diva.Infrastructure.Data.Entities.HookRulePackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppliesToJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivationCondition")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentPackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxEvaluationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ParentPackId");

                    b.HasIndex("TenantId", "IsEnabled", "Priority");

                    b.ToTable("RulePacks");
                });

            modelBuilder.Entity("Diva.Infrastructure.Data.Entities.HookRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PackId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HookPoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Replacement")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderInPack")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopOnMatch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OverridesParentRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxEvaluationMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OverridesParentRuleId");

                    b.HasIndex("PackId", "OrderInPack");

                    b.ToTable("HookRules");
                });

            modelBuilder.Entity("Diva.Infrastructure.Data.Entities.RuleExecutionLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Triggered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Timestamp");

                    b.HasIndex("PackId", "RuleId", "Timestamp");

                    b.ToTable("RuleExecutionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
