// <auto-generated />
using System;
using Diva.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diva.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DivaDbContext))]
    [Migration("20260328090000_AddAgentMaxOutputTokens")]
    partial class AddAgentMaxOutputTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            // Only the modified entities are listed here; the full snapshot is maintained
            // by the DivaDbContextModelSnapshot file.

            modelBuilder.Entity("Diva.Infrastructure.Data.Entities.AgentDefinitionEntity", b =>
                {
                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("INTEGER");
                });

            modelBuilder.Entity("Diva.Infrastructure.Data.Entities.GroupAgentTemplateEntity", b =>
                {
                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("INTEGER");
                });
#pragma warning restore 612, 618
        }
    }
}
